= Rapport d’avancement du groupe “3.4”
PACT groupe xy (Les plus beaux)
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]
:doctype: book
:stem: latexmath
:source-highlighter: coderay
:toc-title: Table des matières
:toc: macro
:sectnums:
:imagesdir: images


// Partie non numérotée
:sectnums!:
== « Teech »

=== Membres du groupe

* Jean Vassoyan
* Arthur Ndoko
* Maxime Lhoustau
* Maxime Tchibozo
* Amyn Kassara
* Louison Braun

=== Tuteur

* Michel Roux

=== Encadrant génie logiciel

* Jean-Claude Moissinac

== Résumé du sujet choisi en français (PAN1)

== Teech: Coach Scolaire Intelligent

Teech est une application Android qui propose des exercices de mathématiques pour étudiants en classe préparatoire.

A la différence d’un simple livre d’annales, Teech s’adapte aux performances de l’élève. 

Lors de la première connexion, l’application demande à chaque élève de renseigner des informations sur son niveau dans les différents chapitres de mathématiques.

Grâce à un algorithme d’Intelligence Artificielle, l’application va alors lui proposer une série d’exercices adaptés à ses difficultés et ciblant les chapitres où il veut progresser. 
Après avoir complété un exercice, et avoir confronté son travail à un corrigé, l’élève remplit une autoévaluation sur l’application.
Ceci permet à l’algorithme de mettre à jour les performances de l'élève dans l’application, et les exercices proposés à l'avenir seront modifiés en conséquence.

Teech permet de faire économiser du temps aux élèves de classe préparatoire: ils peuvent désormais cibler leurs lacunes sans de perdre du temps, et avoir accès à des corrections pertinentes.

Cette application innovante propose une réponse au besoin de modernisation dans le monde des classes préparatoires. 
Elle nous rapproche du campus du futur en permettant aux élèves de classes préparatoire d’enfin travailler sans manuels et dans un monde numérique.

== English Summary (PAN1)

== Teech Smart Classroom Assistant
Teech is an Android app that suggests maths exercises to preparatory class students.

Unlike a simple textbook, Teech adapts itself to each students’ needs.

When a student first connects to Teech, the app asks him to fill in information about his level in different fields of maths.

Using an Artificial Intelligence algorithm, the app suggests a series of exercises adapted to the students’ weaknesses, and focussing on the chapters where he wants to improve.
After completing an exercise and comparing his work to a pre-uploaded answer; the student has to evaluate his own performance on the app.

This allows the algorithm to update the students’ performance in the app, and the exercises that will proposed in the future will be modified adequately.

This innovative app answers the demand for modernisation in the century-old preparatory classes system. Thanks to this app, preparatory class students can save time by focussing on their weaknesses.

Teech brings us one step closer to the “campus of the future”, by allowing preparatory class students to finally work without textbooks in a digital world.



// en PDF on ne peut pas controler la position de la toc
// Macros non supportées
ifndef::backend-pdf[]
== Table des matières
:toc-title:
toc::[]
endif::[]

// On numérote le reste des sections
:sectnums:

== Étude d’antériorité et justification de la proposition (PAN1)

include::proposition/proposition.adoc[Description de la proposition]

include::proposition/etat-de-l-art.adoc[Description de l’état de l’art]

== Scénarios d’usage: "Teech" (PAN1)

include::scenario/scenario.adoc[Scénarios d’usage]

== Architecture du projet (PAN1)

include::architecture/schema.adoc[Schéma d’architecture]

include::architecture/interfaces.adoc[Description des interfaces]

include::architecture/sequence.adoc[Diagramme de séquence]

include::architecture/ihm.adoc[Interface utilisateur graphique]

include::architecture/taches.adoc[Tableau détaillé des tâches]

== Organisation du projet (PAN1)

include::organisation/plannification.adoc[Diagramme de planification temporel des tâches]

include::organisation/repartition.adoc[Répartition des élèves par module]

include::organisation/plan-tests.adoc[Plans de test (PAN2+)]

include::organisation/avancement.adoc[Diagramme d’avancement des tâches (PAN2+)]

'''''

[bibliography]
== Bibliographie (PAN1+)

include::References.adoc[Bibliographie]

'''''

== Annexes

include::annexes/identite.adoc[Fiche d’identité du groupe (PAN1)]

include::annexes/modifications.adoc[Modifications (PAN2+)]

include::annexes/reunions.adoc[Comptes Rendus de réunions]

include::annexes/avancement.adoc[Avancement des modules]

include::annexes/moduleX.adoc[Avancement module X]

include::annexes/moduleY.adoc[Avancement module Y]

include::annexes/moduleAndroid.adoc[Avancement module Android]
